name: Release the helm charts
on:
  push:
    branches:
      - main

jobs:
  charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Install Helm Push
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push.git

      - name: Configure chartmuseum repo
        run: |
          helm repo add vanderveer https://${{ secrets.HELM_USERNAME }}:${{ secrets.HELM_PASSWORD }}@charts.vanderveer.be/vanderveer

      - name: Upload the vanderveer charts
        run: |
          cd ./charts/
          for d in */ ; do
            helm push "./$d" vanderveer --debug;
          done;
          cd ..

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d%H%m%s")"
        shell: bash

      - name: Cache mirror
        uses: actions/cache@v2
        with:
          path: |
            mirror
          key: ${{ runner.os }}-chartmuseum-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-chartmuseum
      - name: Mirror charts
        run: |
          ./scripts/mirror.sh
        env:
          HELM_USERNAME: ${{ secrets.HELM_USERNAME }}
          HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}

  infra:
    runs-on: ubuntu-latest
    needs: charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1

      - run: npm install

      - uses: pulumi/actions@v2
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: up
          stack-name: chartmuseum